### ISSUE TITLE
need libvterm 0.3

### ISSUE THREAD

**Issue by black-desk** [deepin-community/neovim#3]
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found Libuv: /usr/lib/x86_64-linux-gnu/libuv_a.a (Required is at least version "1.28.0")
-- Found Libluv: /usr/lib/x86_64-linux-gnu/lua/5.1/luv.so (Required is at least version "1.43.0")
-- Found Iconv: /usr/include
-- Found Libtermkey: /usr/lib/x86_64-linux-gnu/libtermkey.so (Required is at least version "0.22")
CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Libvterm: Found unsuitable version "0.1", but required is at
  least "0.3" (found /usr/include)
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibvterm.cmake:14 (find_package_handle_standard_args)
  src/nvim/CMakeLists.txt:23 (find_package)

**Comment by black-desk** [comment]
https://salsa.debian.org/jamessan/libvterm might work

**Comment by xzl01** [comment]
https://github.com/deepin-community/libvterm/pull/1
